# Generated by Django 6.0.1 on 2026-02-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_photo_project_cover_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='camera_used',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('travel', 'Travel'), ('portrait', 'Portrait')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
