# Generated by Django 6.0.1 on 2026-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_camera_used_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('prewedding', 'Pre-Wedding'), ('engagement', 'Engagement'), ('portrait', 'Portrait'), ('travel', 'Travel'), ('corporate', 'Corporate Event'), ('concert', 'Concert / Stage Show'), ('fashion', 'Fashion Shoot'), ('product', 'Product Shoot'), ('other', 'Other Event')], max_length=20),
        ),
    ]
