# Generated by Django 6.0.1 on 2026-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientgalleryimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgallery',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
