# Generated by Django 6.0.1 on 2026-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_cover_project_created_at_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('prewedding', 'Pre-Wedding'), ('babyshoot', 'Baby Shoot'), ('advertisement', 'Advertisement'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('corporate', 'Corporate Shoots'), ('bts', 'BTS')], max_length=20),
        ),
    ]
