# Generated by Django 6.0.1 on 2026-04-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('prewedding', 'Pre-Wedding'), ('babyshoot', 'Baby Shoot'), ('advertisement', 'Advertisement'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('corporate', 'Corporate Shoots')], max_length=20),
        ),
    ]
