# Generated by Django 6.0.1 on 2026-04-08 16:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='btsvideo',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
