# Generated by Django 6.0.1 on 2026-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_btsvideo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('prewedding', 'Pre-Wedding'), ('cinematography', 'Cinematography'), ('babyshoot', 'Baby Shoot'), ('advertisement', 'Advertisement'), ('corporate', 'Corporate Shoots'), ('podcast', 'Podcast'), ('documentary', 'Documentary')], max_length=20),
        ),
    ]
