# Generated by Django 6.0.1 on 2026-04-13 16:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('prewedding', 'Pre-Wedding'), ('cinematography', 'Cinematography'), ('babyshoot', 'Baby Shoot'), ('advertisement', 'Advertisement'), ('corporate', 'Corporate Shoot')], max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
